/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask_rpc.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->choice))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->X.X_val, (u_int *) &objp->X.X_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->Y.Y_val, (u_int *) &objp->Y.Y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_averages (XDR *xdrs, averages *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->avg.avg_val, (u_int *) &objp->avg.avg_len, 2,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mul_arr (XDR *xdrs, mul_arr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->array.array_val, (u_int *) &objp->array.array_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
