/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASK_RPC_H_RPCGEN
#define _ASK_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int choice;
	double r;
	int n;
	struct {
		u_int X_len;
		int *X_val;
	} X;
	struct {
		u_int Y_len;
		int *Y_val;
	} Y;
};
typedef struct inputs inputs;

struct averages {
	struct {
		u_int avg_len;
		double *avg_val;
	} avg;
};
typedef struct averages averages;

struct mul_arr {
	struct {
		u_int array_len;
		double *array_val;
	} array;
};
typedef struct mul_arr mul_arr;

#define ASK1_PROG 0x23451111
#define ASK1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALC_INNER_PR 1
extern  int * calc_inner_pr_1(inputs *, CLIENT *);
extern  int * calc_inner_pr_1_svc(inputs *, struct svc_req *);
#define FIND_AVGS 2
extern  averages * find_avgs_1(inputs *, CLIENT *);
extern  averages * find_avgs_1_svc(inputs *, struct svc_req *);
#define CALC_MUL 3
extern  mul_arr * calc_mul_1(inputs *, CLIENT *);
extern  mul_arr * calc_mul_1_svc(inputs *, struct svc_req *);
extern int ask1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALC_INNER_PR 1
extern  int * calc_inner_pr_1();
extern  int * calc_inner_pr_1_svc();
#define FIND_AVGS 2
extern  averages * find_avgs_1();
extern  averages * find_avgs_1_svc();
#define CALC_MUL 3
extern  mul_arr * calc_mul_1();
extern  mul_arr * calc_mul_1_svc();
extern int ask1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);
extern  bool_t xdr_averages (XDR *, averages*);
extern  bool_t xdr_mul_arr (XDR *, mul_arr*);

#else /* K&R C */
extern bool_t xdr_inputs ();
extern bool_t xdr_averages ();
extern bool_t xdr_mul_arr ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASK_RPC_H_RPCGEN */
